<script setup lang="ts">
import { computed, nextTick, onBeforeUnmount, onMounted, reactive, ref, shallowRef, watch } from 'vue'
import { useI18n } from 'vue-i18n'
import { approveAcquisitionStrategiesBatch, approveAcquisitionStrategy, completePipelineReviewCheckpoint, editAcquisitionStrategy, getAcquisitionStage03, getAcquisitionStrategy, listAcquisitionStrategies, rejectAcquisitionStrategy } from '../api'
import type { AcquisitionStage03Summary, AcquisitionStrategy, PipelineDecisionCheckpoint, PipelineDecisionResolution, StrategyPersona, StrategyReviewStatus, StrategyType } from '../types/pipeline'
const props=withDefaults(defineProps<{open:boolean;jobId:string;manualCheckpoint?:PipelineDecisionCheckpoint|null}>(),{manualCheckpoint:null})
const emit=defineEmits<{(e:'close'):void;(e:'strategy-updated',id:number):void;(e:'review-complete',r:PipelineDecisionResolution):void}>()
const {t}=useI18n(); const LIMIT=12
const drawer=ref<HTMLElement|null>(null), queue=shallowRef<AcquisitionStrategy[]>([]), detail=shallowRef<AcquisitionStrategy|null>(null), summary=shallowRef<AcquisitionStage03Summary|null>(null)
const status=ref<StrategyReviewStatus|'all'>('all'), offset=ref(0), total=ref(0), loading=ref(false), pending=ref(''), error=ref(''), reason=ref('')
const form=reactive({persona:'unknown' as StrategyPersona,strategyType:'soft_sell' as StrategyType,commentTemplate:'',dmTemplate:'',actionPlan:'',priority:3})
let generation=0; let controller:AbortController|null=null; let returnFocus:HTMLElement|null=null
const pages=computed(()=>Math.max(1,Math.ceil(total.value/LIMIT))); const page=computed(()=>Math.floor(offset.value/LIMIT)+1)
const checkpoint=computed(()=>props.manualCheckpoint?.jobId===props.jobId&&props.manualCheckpoint.status==='pending'?props.manualCheckpoint:null)
function cancel(){generation++;controller?.abort();controller=null}
function sync(item:AcquisitionStrategy){detail.value=item;form.persona=item.persona;form.strategyType=item.strategyType;form.commentTemplate=item.commentTemplate;form.dmTemplate=item.dmTemplate;form.actionPlan=item.actionPlan;form.priority=item.priority;reason.value=item.reviewReason||''}
async function load(preferred?:number){cancel();const g=generation;controller=new AbortController();loading.value=true;error.value=''
 try{const params={limit:LIMIT,offset:offset.value,...(status.value==='all'?{}:{reviewStatus:status.value})};const [q,s]=await Promise.all([listAcquisitionStrategies(props.jobId,params,controller.signal),getAcquisitionStage03(props.jobId,controller.signal)]);if(g!==generation)return;queue.value=q.data.items;total.value=q.data.total;summary.value=s.data.summary;const id=preferred&&q.data.items.some(x=>x.id===preferred)?preferred:q.data.items[0]?.id;if(id)await select(id,g);else detail.value=null}catch(e){if(g===generation)error.value=t('pipeline.strategyWorkbench.loadError')}finally{if(g===generation)loading.value=false}}
async function select(id:number,g=generation){controller?.abort();controller=new AbortController();try{const {data}=await getAcquisitionStrategy(props.jobId,id,controller.signal);if(g===generation)sync(data.strategy)}catch{if(g===generation)error.value=t('pipeline.strategyWorkbench.loadError')}}
async function authorityReload(id:number){await load(id);if(!detail.value||detail.value.id!==id)throw new Error('refresh')}
function conflictCurrent(e:unknown){const data=(e as {response?:{status?:number;data?:{detail?:{current?:AcquisitionStrategy;message?:string}}}}).response;if(data?.status===409){if(data.data?.detail?.current)sync(data.data.detail.current);error.value=t('pipeline.strategyWorkbench.conflict');return true}return false}
async function mutate(action:'save'|'approve'|'reject'){const current=detail.value;if(!current||pending.value)return;if(action==='reject'&&!reason.value.trim()){error.value=t('pipeline.strategyWorkbench.reasonRequired');return}pending.value=action;error.value='';const g=generation;const jobId=props.jobId
 try{if(action==='save')await editAcquisitionStrategy(props.jobId,current.id,{reviewVersion:current.reviewVersion,...form});else if(action==='approve')await approveAcquisitionStrategy(props.jobId,current.id,{reviewVersion:current.reviewVersion});else await rejectAcquisitionStrategy(props.jobId,current.id,{reviewVersion:current.reviewVersion,reason:reason.value.trim()});if(g!==generation)return;await authorityReload(current.id);emit('strategy-updated',current.id)}catch(e){if(g===generation&&!conflictCurrent(e))error.value=t('pipeline.strategyWorkbench.mutationError')}finally{if(props.jobId===jobId)pending.value=''}}
async function batch(){const items=queue.value.filter(x=>x.reviewStatus==='draft').map(x=>({strategyId:x.id,reviewVersion:x.reviewVersion}));if(!items.length||pending.value)return;pending.value='batch';error.value='';const g=generation;const jobId=props.jobId;try{await approveAcquisitionStrategiesBatch(props.jobId,{items});if(g!==generation)return;await load(detail.value?.id);emit('strategy-updated',detail.value?.id||0)}catch{if(g===generation)error.value=t('pipeline.strategyWorkbench.mutationError')}finally{if(props.jobId===jobId)pending.value=''}}
async function finish(){const c=checkpoint.value;if(!c||pending.value)return;pending.value='finish';try{const {data}=await completePipelineReviewCheckpoint(props.jobId,c.id,{version:c.version});if(checkpoint.value?.id===c.id)emit('review-complete',data.resolution)}catch{error.value=t('pipeline.strategyWorkbench.mutationError')}finally{pending.value=''}}
function close(){cancel();emit('close');nextTick(()=>returnFocus?.focus())}function key(e:KeyboardEvent){if(props.open&&e.key==='Escape')close()}
watch(()=>[props.open,props.jobId] as const,([open])=>{if(open){returnFocus=document.activeElement as HTMLElement;offset.value=0;void load();nextTick(()=>drawer.value?.focus())}else cancel()},{immediate:true})
onMounted(()=>window.addEventListener('keydown',key));onBeforeUnmount(()=>{window.removeEventListener('keydown',key);cancel()})
</script>
<template><Teleport to="body"><div v-if="open" class="backdrop" @click.self="close"><section ref="drawer" class="drawer" role="dialog" aria-modal="true" tabindex="-1">
 <header><div><span>HERMES STRATEGY</span><h2>{{t('pipeline.strategyWorkbench.title')}}</h2><p>{{t('pipeline.strategyWorkbench.jobContext',{jobId})}}</p></div><button @click="close">{{t('common.close')}}</button></header>
 <div class="toolbar"><select v-model="status" @change="offset=0;load()"><option value="all">{{t('pipeline.strategyWorkbench.all')}}</option><option value="draft">{{t('pipeline.strategyWorkbench.status.draft')}}</option><option value="approved">{{t('pipeline.strategyWorkbench.status.approved')}}</option><option value="rejected">{{t('pipeline.strategyWorkbench.status.rejected')}}</option></select><span v-if="summary">{{summary.drafts}} {{t('pipeline.strategyWorkbench.pending')}}</span><button :disabled="!!pending" class="primary" @click="batch">{{t('pipeline.strategyWorkbench.batchApprove')}}</button></div>
 <p v-if="error" class="alert" role="alert">{{error}}</p><div class="layout"><aside><p v-if="loading">{{t('common.loading')}}</p><p v-else-if="!queue.length">{{t('pipeline.strategyWorkbench.empty')}}</p><button v-for="item in queue" :key="item.id" :class="{active:item.id===detail?.id}" @click="select(item.id)"><b>{{item.candidate?.nickname||item.candidate?.username||`#${item.userId}`}}</b><span>{{t(`pipeline.strategyWorkbench.status.${item.reviewStatus}`)}} · v{{item.reviewVersion}}</span></button><footer><button :disabled="offset===0" @click="offset=Math.max(0,offset-LIMIT);load()">{{t('common.prev')}}</button><span>{{page}} / {{pages}}</span><button :disabled="offset+LIMIT>=total" @click="offset+=LIMIT;load()">{{t('common.next')}}</button></footer></aside>
 <main v-if="detail"><section class="candidate"><h3>{{detail.candidate?.nickname||detail.candidate?.username}}</h3><p>@{{detail.candidate?.username}} · {{detail.candidate?.country}} · {{detail.candidate?.followerCount}}</p><p>{{detail.candidate?.bio||t('pipeline.strategyWorkbench.noBio')}}</p></section><div class="form"><label>{{t('pipeline.strategyWorkbench.persona')}}<select v-model="form.persona"><option v-for="v in ['buyer','distributor','manufacturer','contractor','retailer','brand','supplier','competitor','unknown']" :key="v" :value="v">{{v}}</option></select></label><label>{{t('pipeline.strategyWorkbench.type')}}<select v-model="form.strategyType"><option value="soft_sell">soft_sell</option><option value="hard_sell">hard_sell</option><option value="partnership">partnership</option></select></label><label>{{t('pipeline.strategyWorkbench.priority')}}<input v-model.number="form.priority" type="number" min="1" max="5"></label><label class="wide">{{t('pipeline.strategyWorkbench.comment')}}<textarea v-model="form.commentTemplate" maxlength="300"/></label><label class="wide">{{t('pipeline.strategyWorkbench.dm')}}<textarea v-model="form.dmTemplate" maxlength="600"/></label><label class="wide">{{t('pipeline.strategyWorkbench.plan')}}<textarea v-model="form.actionPlan" maxlength="1000"/></label><label class="wide">{{t('pipeline.strategyWorkbench.reason')}}<input v-model="reason" maxlength="500"/></label></div><div class="actions"><button :disabled="!!pending" @click="mutate('save')">{{t('common.save')}}</button><button :disabled="!!pending" class="primary" @click="mutate('approve')">{{t('pipeline.strategyWorkbench.approve')}}</button><button :disabled="!!pending" class="danger" @click="mutate('reject')">{{t('pipeline.strategyWorkbench.reject')}}</button></div></main><main v-else class="empty">{{t('pipeline.strategyWorkbench.select')}}</main></div>
 <footer v-if="checkpoint" class="finish"><span>{{t('pipeline.strategyWorkbench.manualHint')}}</span><button class="primary" :disabled="!!pending" @click="finish">{{t('pipeline.strategyWorkbench.complete')}}</button></footer>
</section></div></Teleport></template>
<style scoped>
.backdrop{position:fixed;inset:0;z-index:2200;background:#11182766;display:flex;justify-content:flex-end}.drawer{width:min(1080px,92vw);height:100%;overflow:auto;background:var(--surface);box-shadow:-18px 0 45px #11182722;outline:0}.drawer>header{position:sticky;top:0;z-index:2;display:flex;justify-content:space-between;align-items:flex-start;padding:18px 22px;border-bottom:1px solid var(--border);background:var(--surface)}header span{color:var(--brand);font:700 10px var(--font-mono);letter-spacing:.12em}h2{margin:4px 0;font-size:20px}header p{margin:0;color:var(--muted);font-size:12px}button,select,input,textarea{min-height:44px;border:1px solid var(--border-strong);border-radius:9px;background:var(--surface);color:var(--fg);padding:8px 11px}.toolbar{display:flex;gap:10px;align-items:center;padding:12px 22px;border-bottom:1px solid var(--border)}.toolbar span{margin-left:auto;color:var(--muted)}.primary{border-color:var(--brand);background:var(--brand);color:white;font-weight:700}.danger{border-color:var(--err);color:var(--err)}.alert{margin:12px 22px;padding:10px;background:var(--err-soft);color:var(--err);border-radius:8px}.layout{display:grid;grid-template-columns:280px 1fr;min-height:calc(100vh - 150px)}aside{padding:12px;border-right:1px solid var(--border);background:var(--bg)}aside>button{display:grid;width:100%;margin-bottom:7px;text-align:left}aside>button span{color:var(--muted);font-size:11px}.active{border-color:var(--brand);box-shadow:0 0 0 1px var(--brand)}aside footer{display:flex;justify-content:space-between;align-items:center}main{padding:20px}.candidate{padding:14px;border-radius:10px;background:var(--bg)}.candidate h3{margin:0}.candidate p{color:var(--muted)}.form{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin-top:16px}.form label{display:grid;gap:6px;color:var(--fg-2);font-size:12px}.wide{grid-column:1/-1}textarea{min-height:78px;resize:vertical}.actions{display:flex;justify-content:flex-end;gap:9px;margin-top:16px}.empty{display:grid;place-items:center;color:var(--muted)}.finish{position:sticky;bottom:0;display:flex;justify-content:space-between;align-items:center;padding:12px 22px;border-top:1px solid var(--border);background:var(--surface)}@media(max-width:720px){.drawer{width:100vw}.layout{grid-template-columns:1fr}.layout aside{border-right:0;border-bottom:1px solid var(--border)}.form{grid-template-columns:1fr}.wide{grid-column:auto}.toolbar{flex-wrap:wrap}.toolbar span{margin-left:0}.finish{align-items:stretch;flex-direction:column;gap:8px}}@media(prefers-reduced-motion:reduce){*{scroll-behavior:auto!important}}
</style>
